/**
 * @module generate-pr
 *
 * Generates GitHub PRs from synthesis atom results.
 *
 * This is the final step in the feedback loop: when synthesis passes
 * with confidence >= 0.8, the feedback loop generates a `synthesis:pr-candidate`
 * signal. This module reads the atom results and creates a branch + PR
 * via the GitHub REST API.
 *
 * GitHub API calls:
 *   1. GET  /repos/{owner}/{repo}/git/ref/heads/main — get main SHA
 *   2. POST /repos/{owner}/{repo}/git/refs           — create branch from main
 *   3. PUT  /repos/{owner}/{repo}/contents/{path}     — create/update files
 *   4. DELETE /repos/{owner}/{repo}/contents/{path}   — delete files
 *   5. POST /repos/{owner}/{repo}/pulls               — create PR
 */

import { applyEdits, type Edit } from '@factory/diff-engine'

// ── Types ────────────────────────────────────────────────────────────

export interface FileChangeV2 {
  path: string
  action: 'create' | 'modify' | 'delete'
  /** Full file content — used for action='create', or legacy action='modify' */
  content?: string
  /** Search/replace edits — used for action='modify' (v2 format) */
  edits?: Edit[]
}

export interface PRGenerationInput {
  signalTitle: string
  proposalId: string
  workGraphId: string
  atomResults: Record<string, {
    atomId: string
    verdict: { decision: string }
    codeArtifact: {
      files: Array<FileChangeV2>
      summary: string
    } | null
  }>
  sourceRefs: string[]
  confidence: number
  /** When the originating signal was created — used for conflict detection */
  signalCreatedAt?: string
  /** Summary of the codebase state the Factory saw when generating this proposal */
  specContentSummary?: string
}

export interface PRGenerationResult {
  success: boolean
  prUrl?: string
  branchName?: string
  error?: string
  filesWritten: number
  /** Files that were expected to exist (modify action) but were not found */
  filesNotFound?: string[]
  /** Conflict warnings surfaced during PR creation */
  warnings?: string[]
}

// ── Helpers ─────────────────────────────────────────────────────────

const MAX_BRANCH_LENGTH = 50

/**
 * Build a sanitized branch name from a proposalId.
 * Format: factory/{proposalId} — lowercase, truncated to 50 chars.
 */
export function buildBranchName(proposalId: string): string {
  const sanitized = proposalId
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9\-]/g, '')

  const prefix = 'factory/'
  const maxSlugLength = MAX_BRANCH_LENGTH - prefix.length
  const slug = sanitized.slice(0, maxSlugLength)

  return `${prefix}${slug}`
}

/**
 * Build the markdown body for the PR description.
 * Includes lineage, atom summaries, and confidence score.
 */
export function buildPRBody(input: PRGenerationInput): string {
  const sections: string[] = []

  // Header
  sections.push(`## Factory-Generated PR`)
  sections.push('')
  sections.push(`**WorkGraph:** \`${input.workGraphId}\``)
  sections.push(`**Proposal:** \`${input.proposalId}\``)
  sections.push(`**Confidence:** ${input.confidence}`)
  sections.push('')

  // Lineage
  sections.push(`### Lineage`)
  sections.push('')
  if (input.sourceRefs.length > 0) {
    for (const ref of input.sourceRefs) {
      sections.push(`- \`${ref}\``)
    }
  } else {
    sections.push('_No lineage refs_')
  }
  sections.push('')

  // Atom summaries
  sections.push(`### Atom Results`)
  sections.push('')
  const entries = Object.entries(input.atomResults ?? {})
  if (entries.length === 0) {
    sections.push('_No atom results_')
  } else {
    for (const [atomId, atomResult] of entries) {
      const verdict = atomResult.verdict.decision
      const summary = atomResult.codeArtifact?.summary ?? 'No code artifact'
      const fileCount = atomResult.codeArtifact?.files?.length ?? 0
      sections.push(`- **${atomId}** (${verdict}): ${summary} — ${fileCount} file(s)`)
    }
  }
  sections.push('')

  // Conflict detection
  sections.push(`### Conflict Detection`)
  sections.push('')
  if (input.signalCreatedAt) {
    sections.push(`- **Signal created at:** \`${input.signalCreatedAt}\``)
  }
  if (input.specContentSummary) {
    sections.push(`- **Codebase state seen by Factory:** ${input.specContentSummary}`)
  }
  sections.push(`- **PR created at:** \`${new Date().toISOString()}\``)
  sections.push('')
  sections.push('> **Warning:** The Factory generates code from a codebase snapshot. ' +
    'If the repo has diverged since the signal was created, file conflicts may exist. ' +
    'Review carefully before merging.')
  sections.push('')

  // Footer
  sections.push('---')
  sections.push('_Generated by the Function Factory feedback loop._')

  return sections.join('\n')
}

// ── GitHub API helpers ──────────────────────────────────────────────

function apiHeaders(token: string): Record<string, string> {
  return {
    'Authorization': `Bearer ${token}`,
    'Accept': 'application/vnd.github+json',
    'Content-Type': 'application/json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'ff-pipeline',
  }
}

/**
 * Decode a base64 string (from GitHub API) to UTF-8 text.
 * GitHub returns file content as base64 with possible newlines.
 */
function fromBase64(encoded: string): string {
  const cleaned = encoded.replace(/\n/g, '')
  const binary = atob(cleaned)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i)
  }
  return new TextDecoder().decode(bytes)
}

/**
 * Base64-encode a string, handling UTF-8 correctly.
 * btoa() only handles Latin-1; this uses TextEncoder for full Unicode support.
 */
function toBase64(str: string): string {
  const bytes = new TextEncoder().encode(str)
  let binary = ''
  for (const byte of bytes) {
    binary += String.fromCharCode(byte)
  }
  return btoa(binary)
}

function apiUrl(owner: string, repo: string, path: string): string {
  return `https://api.github.com/repos/${owner}/${repo}${path}`
}

// ── Main ────────────────────────────────────────────────────────────

/**
 * Generate a GitHub PR from synthesis atom results.
 *
 * Steps:
 *   1. Get main branch SHA
 *   2. Create branch from main
 *   3. Write files from passing atoms
 *   4. Create PR
 */
export async function generatePR(
  input: PRGenerationInput,
  githubToken: string,
  repoOwner: string,
  repoName: string,
): Promise<PRGenerationResult> {
  const branchName = buildBranchName(input.proposalId)
  let filesWritten = 0

  try {
    const headers = apiHeaders(githubToken)

    // ── Step 1: Get main branch SHA ──
    const mainRefRes = await fetch(
      apiUrl(repoOwner, repoName, '/git/ref/heads/main'),
      { method: 'GET', headers },
    )

    if (!mainRefRes.ok) {
      const errorBody = await mainRefRes.text()
      return {
        success: false,
        branchName,
        error: `Failed to get main ref (${mainRefRes.status}): ${errorBody}`,
        filesWritten: 0,
      }
    }

    const mainRef = await mainRefRes.json() as { object: { sha: string } }
    const mainSha = mainRef.object.sha

    // ── Step 2: Create branch from main ──
    const createBranchRes = await fetch(
      apiUrl(repoOwner, repoName, '/git/refs'),
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          ref: `refs/heads/${branchName}`,
          sha: mainSha,
        }),
      },
    )

    if (!createBranchRes.ok) {
      const errorBody = await createBranchRes.text()
      return {
        success: false,
        branchName,
        error: `Failed to create branch (${createBranchRes.status}): ${errorBody}`,
        filesWritten: 0,
      }
    }

    // ── Step 3: Write files from passing atoms ──
    // Group files by path across atoms (Architect condition #8: serialize per path)
    const filesByPath = new Map<string, FileChangeV2[]>()
    const filesNotFound: string[] = []
    const warnings: string[] = []

    for (const [, atomResult] of Object.entries(input.atomResults ?? {})) {
      if (atomResult.verdict.decision !== 'pass') continue
      if (!atomResult.codeArtifact?.files) continue

      for (const file of atomResult.codeArtifact.files) {
        const existing = filesByPath.get(file.path)
        if (existing) {
          existing.push(file)
        } else {
          filesByPath.set(file.path, [file])
        }
      }
    }

    for (const [filePath, fileChanges] of filesByPath) {
      const primaryAction = fileChanges[fileChanges.length - 1]!.action

      if (primaryAction === 'delete') {
        const getFileRes = await fetch(
          apiUrl(repoOwner, repoName, `/contents/${filePath}?ref=${branchName}`),
          { method: 'GET', headers },
        )

        let fileSha: string | undefined
        if (getFileRes.ok) {
          const fileData = await getFileRes.json() as { sha: string }
          fileSha = fileData.sha
        } else {
          filesNotFound.push(filePath)
          warnings.push(`Delete target not found: ${filePath}`)
        }

        await fetch(
          apiUrl(repoOwner, repoName, `/contents/${filePath}`),
          {
            method: 'DELETE',
            headers,
            body: JSON.stringify({
              message: `[Factory] Delete ${filePath}`,
              branch: branchName,
              sha: fileSha ?? '',
            }),
          },
        )
        filesWritten++
        continue
      }

      // create or modify — fetch existing file state
      const getFileRes = await fetch(
        apiUrl(repoOwner, repoName, `/contents/${filePath}?ref=${branchName}`),
        { method: 'GET', headers },
      ).catch(() => null)

      let existingSha: string | undefined
      let existingContent: string | undefined

      if (getFileRes?.ok) {
        const fileData = await getFileRes.json() as { sha: string; content: string }
        existingSha = fileData.sha
        existingContent = fromBase64(fileData.content)
      } else if (primaryAction === 'modify') {
        filesNotFound.push(filePath)
        warnings.push(`Modify target not found on branch, treating as create: ${filePath}`)
      }

      // Resolve final content — diff-based edits or legacy full content
      let finalContent: string | undefined

      // Merge edits from all atoms targeting this file
      const allEdits: Edit[] = []
      let hasLegacyContent = false
      let legacyContent = ''

      for (const change of fileChanges) {
        if (change.edits && change.edits.length > 0) {
          allEdits.push(...change.edits)
        } else if (change.content !== undefined) {
          hasLegacyContent = true
          legacyContent = change.content
          warnings.push(`Legacy full-content format used for: ${filePath}`)
        }
      }

      if (allEdits.length > 0 && existingContent !== undefined) {
        // v2 path: apply search/replace edits to existing content
        const result = applyEdits(existingContent, allEdits)
        if (result.success) {
          finalContent = result.content
        } else {
          const failureDetails = result.failedEdits
            .map(f => `${f.reason}: "${f.edit.search.slice(0, 60)}..."`)
            .join('; ')
          warnings.push(`Edit application partial failure on ${filePath}: ${failureDetails}`)
          if (result.appliedEdits > 0) {
            finalContent = result.content
          } else {
            warnings.push(`All edits failed for ${filePath}, skipping file`)
            continue
          }
        }
      } else if (allEdits.length > 0 && existingContent === undefined) {
        warnings.push(`Edits provided but no existing file to patch: ${filePath}`)
        continue
      } else if (hasLegacyContent) {
        // Fallback: legacy full-content replacement
        finalContent = legacyContent
      } else {
        warnings.push(`No content or edits for ${filePath}, skipping`)
        continue
      }

      await fetch(
        apiUrl(repoOwner, repoName, `/contents/${filePath}`),
        {
          method: 'PUT',
          headers,
          body: JSON.stringify({
            message: `[Factory] ${primaryAction === 'create' ? 'Create' : 'Update'} ${filePath}`,
            content: toBase64(finalContent),
            branch: branchName,
            ...(existingSha ? { sha: existingSha } : {}),
          }),
        },
      )
      filesWritten++
    }

    // ── Step 4: Create draft PR ──
    // Append file-not-found warnings to PR body if any
    let prBody = buildPRBody(input)
    if (filesNotFound.length > 0) {
      prBody += '\n\n### File Warnings\n\n'
      prBody += '> The following files could not be found at their expected paths:\n\n'
      for (const f of filesNotFound) {
        prBody += `- \`${f}\`\n`
      }
    }

    const createPRRes = await fetch(
      apiUrl(repoOwner, repoName, '/pulls'),
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          title: `[Factory] ${input.signalTitle}`,
          body: prBody,
          head: branchName,
          base: 'main',
          draft: true,
        }),
      },
    )

    if (!createPRRes.ok) {
      const errorBody = await createPRRes.text()
      return {
        success: false,
        branchName,
        error: `Failed to create PR (${createPRRes.status}): ${errorBody}`,
        filesWritten,
      }
    }

    const pr = await createPRRes.json() as { html_url: string; number: number }

    // ── Step 5: Label the PR ──
    // Create label if it doesn't exist (409 = already exists, ignore)
    await fetch(
      apiUrl(repoOwner, repoName, '/labels'),
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          name: 'factory-generated',
          color: '7057ff',
          description: 'PR generated by the Function Factory feedback loop',
        }),
      },
    ).catch(() => {}) // Ignore label creation errors (409, network, etc.)

    // Apply label to the PR
    await fetch(
      apiUrl(repoOwner, repoName, `/issues/${pr.number}/labels`),
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          labels: ['factory-generated'],
        }),
      },
    ).catch(() => {}) // Label application is best-effort

    return {
      success: true,
      prUrl: pr.html_url,
      branchName,
      filesWritten,
      ...(filesNotFound.length > 0 ? { filesNotFound } : {}),
      ...(warnings.length > 0 ? { warnings } : {}),
    }
  } catch (err) {
    return {
      success: false,
      branchName,
      error: err instanceof Error ? err.message : String(err),
      filesWritten,
    }
  }
}
