/**
 * @module generate-pr
 *
 * Generates GitHub PRs from synthesis atom results.
 *
 * This is the final step in the feedback loop: when synthesis passes
 * with confidence >= 0.8, the feedback loop generates a `synthesis:pr-candidate`
 * signal. This module reads the atom results and creates a branch + PR
 * via the GitHub REST API.
 *
 * GitHub API calls:
 *   1. GET  /repos/{owner}/{repo}/git/ref/heads/main — get main SHA
 *   2. POST /repos/{owner}/{repo}/git/refs           — create branch from main
 *   3. PUT  /repos/{owner}/{repo}/contents/{path}     — create/update files
 *   4. DELETE /repos/{owner}/{repo}/contents/{path}   — delete files
 *   5. POST /repos/{owner}/{repo}/pulls               — create PR
 */

// ── Types ────────────────────────────────────────────────────────────

export interface PRGenerationInput {
  signalTitle: string
  proposalId: string
  workGraphId: string
  atomResults: Record<string, {
    atomId: string
    verdict: { decision: string }
    codeArtifact: {
      files: Array<{ path: string; content: string; action: 'create' | 'modify' | 'delete' }>
      summary: string
    } | null
  }>
  sourceRefs: string[]
  confidence: number
  /** When the originating signal was created — used for conflict detection */
  signalCreatedAt?: string
  /** Summary of the codebase state the Factory saw when generating this proposal */
  specContentSummary?: string
}

export interface PRGenerationResult {
  success: boolean
  prUrl?: string
  branchName?: string
  error?: string
  filesWritten: number
  /** Files that were expected to exist (modify action) but were not found */
  filesNotFound?: string[]
  /** Conflict warnings surfaced during PR creation */
  warnings?: string[]
}

// ── Helpers ─────────────────────────────────────────────────────────

const MAX_BRANCH_LENGTH = 50

/**
 * Build a sanitized branch name from a proposalId.
 * Format: factory/{proposalId} — lowercase, truncated to 50 chars.
 */
export function buildBranchName(proposalId: string): string {
  const sanitized = proposalId
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9\-]/g, '')

  const prefix = 'factory/'
  const maxSlugLength = MAX_BRANCH_LENGTH - prefix.length
  const slug = sanitized.slice(0, maxSlugLength)

  return `${prefix}${slug}`
}

/**
 * Build the markdown body for the PR description.
 * Includes lineage, atom summaries, and confidence score.
 */
export function buildPRBody(input: PRGenerationInput): string {
  const sections: string[] = []

  // Header
  sections.push(`## Factory-Generated PR`)
  sections.push('')
  sections.push(`**WorkGraph:** \`${input.workGraphId}\``)
  sections.push(`**Proposal:** \`${input.proposalId}\``)
  sections.push(`**Confidence:** ${input.confidence}`)
  sections.push('')

  // Lineage
  sections.push(`### Lineage`)
  sections.push('')
  if (input.sourceRefs.length > 0) {
    for (const ref of input.sourceRefs) {
      sections.push(`- \`${ref}\``)
    }
  } else {
    sections.push('_No lineage refs_')
  }
  sections.push('')

  // Atom summaries
  sections.push(`### Atom Results`)
  sections.push('')
  const entries = Object.entries(input.atomResults)
  if (entries.length === 0) {
    sections.push('_No atom results_')
  } else {
    for (const [atomId, atomResult] of entries) {
      const verdict = atomResult.verdict.decision
      const summary = atomResult.codeArtifact?.summary ?? 'No code artifact'
      const fileCount = atomResult.codeArtifact?.files?.length ?? 0
      sections.push(`- **${atomId}** (${verdict}): ${summary} — ${fileCount} file(s)`)
    }
  }
  sections.push('')

  // Conflict detection
  sections.push(`### Conflict Detection`)
  sections.push('')
  if (input.signalCreatedAt) {
    sections.push(`- **Signal created at:** \`${input.signalCreatedAt}\``)
  }
  if (input.specContentSummary) {
    sections.push(`- **Codebase state seen by Factory:** ${input.specContentSummary}`)
  }
  sections.push(`- **PR created at:** \`${new Date().toISOString()}\``)
  sections.push('')
  sections.push('> **Warning:** The Factory generates code from a codebase snapshot. ' +
    'If the repo has diverged since the signal was created, file conflicts may exist. ' +
    'Review carefully before merging.')
  sections.push('')

  // Footer
  sections.push('---')
  sections.push('_Generated by the Function Factory feedback loop._')

  return sections.join('\n')
}

// ── GitHub API helpers ──────────────────────────────────────────────

function apiHeaders(token: string): Record<string, string> {
  return {
    'Authorization': `Bearer ${token}`,
    'Accept': 'application/vnd.github+json',
    'Content-Type': 'application/json',
    'X-GitHub-Api-Version': '2022-11-28',
  }
}

function apiUrl(owner: string, repo: string, path: string): string {
  return `https://api.github.com/repos/${owner}/${repo}${path}`
}

// ── Main ────────────────────────────────────────────────────────────

/**
 * Generate a GitHub PR from synthesis atom results.
 *
 * Steps:
 *   1. Get main branch SHA
 *   2. Create branch from main
 *   3. Write files from passing atoms
 *   4. Create PR
 */
export async function generatePR(
  input: PRGenerationInput,
  githubToken: string,
  repoOwner: string,
  repoName: string,
): Promise<PRGenerationResult> {
  const branchName = buildBranchName(input.proposalId)
  let filesWritten = 0

  try {
    const headers = apiHeaders(githubToken)

    // ── Step 1: Get main branch SHA ──
    const mainRefRes = await fetch(
      apiUrl(repoOwner, repoName, '/git/ref/heads/main'),
      { method: 'GET', headers },
    )

    if (!mainRefRes.ok) {
      const errorBody = await mainRefRes.text()
      return {
        success: false,
        branchName,
        error: `Failed to get main ref (${mainRefRes.status}): ${errorBody}`,
        filesWritten: 0,
      }
    }

    const mainRef = await mainRefRes.json() as { object: { sha: string } }
    const mainSha = mainRef.object.sha

    // ── Step 2: Create branch from main ──
    const createBranchRes = await fetch(
      apiUrl(repoOwner, repoName, '/git/refs'),
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          ref: `refs/heads/${branchName}`,
          sha: mainSha,
        }),
      },
    )

    if (!createBranchRes.ok) {
      const errorBody = await createBranchRes.text()
      return {
        success: false,
        branchName,
        error: `Failed to create branch (${createBranchRes.status}): ${errorBody}`,
        filesWritten: 0,
      }
    }

    // ── Step 3: Write files from passing atoms ──
    const filesToWrite: Array<{ path: string; content: string; action: 'create' | 'modify' | 'delete' }> = []
    const filesNotFound: string[] = []
    const warnings: string[] = []

    for (const [, atomResult] of Object.entries(input.atomResults)) {
      // Skip atoms that did not pass
      if (atomResult.verdict.decision !== 'pass') continue
      // Skip atoms without code artifacts
      if (!atomResult.codeArtifact?.files) continue

      for (const file of atomResult.codeArtifact.files) {
        filesToWrite.push(file)
      }
    }

    for (const file of filesToWrite) {
      if (file.action === 'delete') {
        // For delete, we need to get the file SHA first
        const getFileRes = await fetch(
          apiUrl(repoOwner, repoName, `/contents/${file.path}?ref=${branchName}`),
          { method: 'GET', headers },
        )

        let fileSha: string | undefined
        if (getFileRes.ok) {
          const fileData = await getFileRes.json() as { sha: string }
          fileSha = fileData.sha
        } else {
          filesNotFound.push(file.path)
          warnings.push(`Delete target not found: ${file.path}`)
        }

        await fetch(
          apiUrl(repoOwner, repoName, `/contents/${file.path}`),
          {
            method: 'DELETE',
            headers,
            body: JSON.stringify({
              message: `[Factory] Delete ${file.path}`,
              branch: branchName,
              sha: fileSha ?? '',
            }),
          },
        )
      } else {
        // create or modify — always check if file exists on this branch
        const getFileRes = await fetch(
          apiUrl(repoOwner, repoName, `/contents/${file.path}?ref=${branchName}`),
          { method: 'GET', headers },
        ).catch(() => null)

        let existingSha: string | undefined
        if (getFileRes?.ok) {
          const fileData = await getFileRes.json() as { sha: string }
          existingSha = fileData.sha
        } else if (file.action === 'modify') {
          // File expected to exist for modify but doesn't — track as conflict
          filesNotFound.push(file.path)
          warnings.push(`Modify target not found on branch, treating as create: ${file.path}`)
        }

        await fetch(
          apiUrl(repoOwner, repoName, `/contents/${file.path}`),
          {
            method: 'PUT',
            headers,
            body: JSON.stringify({
              message: `[Factory] ${file.action === 'create' ? 'Create' : 'Update'} ${file.path}`,
              content: btoa(file.content),
              branch: branchName,
              ...(existingSha ? { sha: existingSha } : {}),
            }),
          },
        )
      }

      filesWritten++
    }

    // ── Step 4: Create draft PR ──
    // Append file-not-found warnings to PR body if any
    let prBody = buildPRBody(input)
    if (filesNotFound.length > 0) {
      prBody += '\n\n### File Warnings\n\n'
      prBody += '> The following files could not be found at their expected paths:\n\n'
      for (const f of filesNotFound) {
        prBody += `- \`${f}\`\n`
      }
    }

    const createPRRes = await fetch(
      apiUrl(repoOwner, repoName, '/pulls'),
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          title: `[Factory] ${input.signalTitle}`,
          body: prBody,
          head: branchName,
          base: 'main',
          draft: true,
        }),
      },
    )

    if (!createPRRes.ok) {
      const errorBody = await createPRRes.text()
      return {
        success: false,
        branchName,
        error: `Failed to create PR (${createPRRes.status}): ${errorBody}`,
        filesWritten,
      }
    }

    const pr = await createPRRes.json() as { html_url: string; number: number }

    // ── Step 5: Label the PR ──
    // Create label if it doesn't exist (409 = already exists, ignore)
    await fetch(
      apiUrl(repoOwner, repoName, '/labels'),
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          name: 'factory-generated',
          color: '7057ff',
          description: 'PR generated by the Function Factory feedback loop',
        }),
      },
    ).catch(() => {}) // Ignore label creation errors (409, network, etc.)

    // Apply label to the PR
    await fetch(
      apiUrl(repoOwner, repoName, `/issues/${pr.number}/labels`),
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          labels: ['factory-generated'],
        }),
      },
    ).catch(() => {}) // Label application is best-effort

    return {
      success: true,
      prUrl: pr.html_url,
      branchName,
      filesWritten,
      ...(filesNotFound.length > 0 ? { filesNotFound } : {}),
      ...(warnings.length > 0 ? { warnings } : {}),
    }
  } catch (err) {
    return {
      success: false,
      branchName,
      error: err instanceof Error ? err.message : String(err),
      filesWritten,
    }
  }
}
