import { describe, expect, it } from "vitest"
import { MergeReadinessPack } from "./sdlc.js"

const baseMergeReadinessPack = {
  _key: "MRP-MOTE4M1R-G7I0-71",
  id: "MRP-MOTE4M1R-G7I0-71",
  functionId: "FN-MOTDWVR2-W7UN",
  workGraphId: "WG-MOTE4M1R-G7I0",
  pipelineInstanceId: "b1b51f73-416d-4d87-90a5-9ccaa12bec76",
  functionalCompleteness: {
    passed: true,
    acceptanceCriteria: [
      {
        criterion: "Runtime verification artifact is materialized with tests",
        met: true,
        evidence: "workers/ff-pipeline/src/runtime-verification.test.ts",
      },
    ],
  },
  soundVerification: {
    passed: true,
    testPlan: "Runtime verification test harness plus ff-pipeline suite",
    newTestCases: [
      {
        name: "records a validated synthesis smoke result",
        type: "unit",
        result: "pass",
      },
    ],
    fidelityVerificationReportId: "CR-MOTE4M1R-GATE2",
    gate2ReportId: "CR-MOTE4M1R-GATE2",
  },
  seHygiene: {
    passed: true,
    mentorRuleCompliance: [
      {
        ruleId: "MR-STRICT-TYPESCRIPT",
        rule: "Use strict TypeScript and colocated tests",
        compliant: true,
      },
    ],
  },
  rationale: {
    approach: "Materialize the runtime verification artifact generated by synthesis",
    tradeoffsConsidered: "Kept local harness separate from generated implementation artifact",
    prDescription: "Factory dogfood materialization for WG-MOTE4M1R-G7I0",
    crpsResolved: [],
  },
  auditability: {
    prdId: "PRD-MOTE4M1R-G7I0",
    workGraphId: "WG-MOTE4M1R-G7I0",
    semanticReviewId: "SRR-MOTE4M1R-G7I0",
    coherenceVerificationReportId: "CR-MOTE4M1R-GATE1",
    gate1ReportId: "CR-MOTE4M1R-GATE1",
    fidelityVerificationReportId: "CR-MOTE4M1R-GATE2",
    gate2ReportId: "CR-MOTE4M1R-GATE2",
    modelBindings: {
      planner: { provider: "factory-runtime", model: "observed" },
    },
    mentorRulesApplied: [],
    totalTokenUsage: 0,
    totalCost: 0,
    executionDurationMs: 1,
  },
  ciEvidence: {
    status: "passed",
    checksPassed: ["Factory PR Gate", "Typecheck", "Test"],
    checksFailed: [],
    checksPending: [],
    commitSha: "e933510c98dc29dabfb635bb49e47667eefdbf1c",
  },
  verdict: "merge-ready",
  verdictRationale: "Synthesis passed, verification passed, and CI passed.",
  source_refs: ["FN-MOTDWVR2-W7UN", "WG-MOTE4M1R-G7I0"],
  createdAt: "2026-05-06T04:00:00.000Z",
}

describe("MergeReadinessPack", () => {
  it("accepts Fidelity Verification report ids alongside Gate 2 compatibility ids", () => {
    expect(MergeReadinessPack.safeParse(baseMergeReadinessPack).success).toBe(true)
  })
})
