/**
 * OWL properties extracted from factory-ontology.ttl
 *
 * Both ObjectProperties (relationships) and DatatypeProperties (attributes).
 */

import type { OntologyProperty } from './index.js'

export const ONTOLOGY_PROPERTIES: OntologyProperty[] = [

  // ═══════════════════════════════════════════════════════════════
  // OBJECT PROPERTIES — Relationships between things
  // ═══════════════════════════════════════════════════════════════

  // -- Lineage --
  {
    _key: 'derivesFrom',
    uri: 'ff:derivesFrom',
    label: 'Derives From',
    propertyType: 'object',
    domain: 'SpecificationArtifact',
    range: 'SpecificationArtifact',
    comment: 'Upstream derivation. Every non-Signal artifact MUST have at least one.',
  },
  {
    _key: 'derivedFromSignal',
    uri: 'ff:derivedFromSignal',
    label: 'Derived From Signal',
    propertyType: 'object',
    domain: 'Pressure',
    range: 'Signal',
    superProperty: 'derivesFrom',
    comment: 'Pressure derives from Signal.',
  },
  {
    _key: 'compiledFrom',
    uri: 'ff:compiledFrom',
    label: 'Compiled From',
    propertyType: 'object',
    domain: 'WorkGraph',
    range: 'FunctionProposal',
    superProperty: 'derivesFrom',
    comment: 'WorkGraph compiled from FunctionProposal.',
  },
  {
    _key: 'synthesizedFrom',
    uri: 'ff:synthesizedFrom',
    label: 'Synthesized From',
    propertyType: 'object',
    domain: 'ExecutionArtifact',
    range: 'WorkGraph',
    comment: 'Execution artifact synthesized from WorkGraph.',
  },

  // -- Production --
  {
    _key: 'producedBy',
    uri: 'ff:producedBy',
    label: 'Produced By',
    propertyType: 'object',
    domain: 'ExecutionArtifact',
    range: 'AgentRole',
    comment: 'Which agent role produced this artifact.',
  },
  {
    _key: 'producedAt',
    uri: 'ff:producedAt',
    label: 'Produced At',
    propertyType: 'object',
    domain: 'ExecutionArtifact',
    range: 'PipelineStage',
    comment: 'Which pipeline stage produced this artifact.',
  },

  // -- Validation --
  {
    _key: 'validatedBy',
    uri: 'ff:validatedBy',
    label: 'Validated By',
    propertyType: 'object',
    domain: 'SpecificationArtifact',
    range: 'Gate',
    comment: 'Which gate validated this artifact.',
  },
  {
    _key: 'reviewedBy',
    uri: 'ff:reviewedBy',
    label: 'Reviewed By',
    propertyType: 'object',
    domain: 'WorkGraph | CodeArtifact | PRDDraft',
    range: 'AgentRole',
    comment: 'EVERY WorkGraph, CodeArtifact, and PRDDraft MUST be reviewed.',
  },
  {
    _key: 'gateResult',
    uri: 'ff:gateResult',
    label: 'Gate Result',
    propertyType: 'object',
    domain: 'Gate',
    range: 'CoverageReport',
    comment: 'Gate produces a CoverageReport.',
  },

  // -- Governance --
  {
    _key: 'constrainedBy',
    uri: 'ff:constrainedBy',
    label: 'Constrained By',
    propertyType: 'object',
    domain: 'AgentRole',
    range: 'MentorScript',
    comment: 'MentorScript rules that constrain this agent behavior.',
  },
  {
    _key: 'escalatesVia',
    uri: 'ff:escalatesVia',
    label: 'Escalates Via',
    propertyType: 'object',
    domain: 'AgentRole',
    range: 'ConsultationRequestPack',
    comment: 'When uncertain, agents MUST escalate via CRP.',
  },
  {
    _key: 'resolvedBy',
    uri: 'ff:resolvedBy',
    label: 'Resolved By',
    propertyType: 'object',
    domain: 'ConsultationRequestPack',
    range: 'VersionControlledResolution',
    comment: 'CRP resolved by a VCR.',
  },
  {
    _key: 'approvedBy',
    uri: 'ff:approvedBy',
    label: 'Approved By',
    propertyType: 'object',
    domain: 'MergeReadinessPack',
    range: 'VersionControlledResolution',
    comment: 'MRP approved by a VCR.',
  },
  {
    _key: 'relatedArtifact',
    uri: 'ff:relatedArtifact',
    label: 'Related Artifact',
    propertyType: 'object',
    domain: 'ConsultationRequestPack',
    range: 'Thing',
    comment: 'The artifact that triggered this CRP (used in C7 confidence escalation).',
  },
  {
    _key: 'groundedIn',
    uri: 'ff:groundedIn',
    label: 'Grounded In',
    propertyType: 'object',
    domain: 'CritiqueReport',
    range: 'Signal',
    comment: 'The originating Signal whose specContent grounds this review (C10).',
  },
  {
    _key: 'communicatesVia',
    uri: 'ff:communicatesVia',
    label: 'Communicates Via',
    propertyType: 'object',
    domain: 'Workflow',
    range: 'Queue',
    comment: 'Workflows MUST communicate with DOs via Queue, not direct RPC (C16).',
  },

  // -- Agent Capabilities --
  {
    _key: 'hasTools',
    uri: 'ff:hasTools',
    label: 'Has Tools',
    propertyType: 'object',
    domain: 'AgentRole',
    range: 'Tool',
    comment: 'Tools available to this agent. An agent without tools is not an agent.',
  },
  {
    _key: 'hasPermission',
    uri: 'ff:hasPermission',
    label: 'Has Permission',
    propertyType: 'object',
    domain: 'AgentRole',
    range: 'Permission',
    comment: 'Permissions assigned to this agent role.',
  },
  {
    _key: 'hasMemoryAccess',
    uri: 'ff:hasMemoryAccess',
    label: 'Has Memory Access',
    propertyType: 'object',
    domain: 'AgentRole',
    range: 'MemoryAccess',
    comment: 'What institutional memory an agent loads at session start.',
  },
  {
    _key: 'runsIn',
    uri: 'ff:runsIn',
    label: 'Runs In',
    propertyType: 'object',
    domain: 'AgentRole',
    range: 'ExecutionEnvironment',
    comment: 'Where the agent runs.',
  },
  {
    _key: 'usesModel',
    uri: 'ff:usesModel',
    label: 'Uses Model',
    propertyType: 'object',
    domain: 'AgentRole',
    range: 'ModelRoute',
    comment: 'Model route used by this agent role.',
  },

  // -- Infrastructure --
  {
    _key: 'persistedIn',
    uri: 'ff:persistedIn',
    label: 'Persisted In',
    propertyType: 'object',
    domain: 'Thing',
    range: 'ArangoCollection',
    comment: 'Which ArangoDB collection this artifact is stored in.',
  },
  {
    _key: 'triggeredBy',
    uri: 'ff:triggeredBy',
    label: 'Triggered By',
    propertyType: 'object',
    domain: 'PipelineStage',
    range: 'PipelineStage',
    comment: 'Pipeline stage trigger chain.',
  },

  // -- Lifecycle --
  {
    _key: 'hasLifecycleState',
    uri: 'ff:hasLifecycleState',
    label: 'Has Lifecycle State',
    propertyType: 'object',
    domain: 'FunctionProposal',
    range: 'FunctionLifecycleState',
    comment: 'Current lifecycle state of a FunctionProposal.',
  },
  {
    _key: 'detectedBy',
    uri: 'ff:detectedBy',
    label: 'Detected By',
    propertyType: 'object',
    domain: 'Invariant',
    range: 'DetectorSpec',
    comment: 'An Invariant without a Detector is a wish. Gate 1 rejects.',
  },
  {
    _key: 'allowedTransition',
    uri: 'ff:allowedTransition',
    label: 'Allowed Transition',
    propertyType: 'object',
    domain: 'FunctionLifecycleState',
    range: 'FunctionLifecycleState',
    comment: 'Allowed lifecycle state transitions. Transitions not in this graph are forbidden.',
  },
  {
    _key: 'transitionRequires',
    uri: 'ff:transitionRequires',
    label: 'Transition Requires',
    propertyType: 'object',
    domain: 'FunctionLifecycleState',
    range: 'Gate',
    comment: 'Gate that must pass for this transition to be allowed.',
  },

  // ═══════════════════════════════════════════════════════════════
  // DATA PROPERTIES — Typed attributes
  // ═══════════════════════════════════════════════════════════════

  {
    _key: 'artifactId',
    uri: 'ff:artifactId',
    label: 'Artifact ID',
    propertyType: 'datatype',
    domain: 'Thing',
    range: 'xsd:string',
    comment: 'Factory artifact ID matching pattern: PREFIX-QUALIFIER-NAME.',
  },
  {
    _key: 'specContent',
    uri: 'ff:specContent',
    label: 'Spec Content',
    propertyType: 'datatype',
    domain: 'Thing',
    range: 'xsd:string',
    comment: 'The verbatim specification text. Must propagate through entire derivation chain without loss.',
  },
  {
    _key: 'sourceRefs',
    uri: 'ff:sourceRefs',
    label: 'Source Refs',
    propertyType: 'datatype',
    domain: 'Thing',
    range: 'xsd:string',
    comment: 'Array of upstream artifact IDs. Empty only for Stage 1 Signals.',
  },
  {
    _key: 'explicitness',
    uri: 'ff:explicitness',
    label: 'Explicitness',
    propertyType: 'datatype',
    domain: 'Thing',
    range: 'xsd:string',
    comment: 'Whether this field is explicit (stated) or inferred (derived). Values: explicit, inferred.',
  },
  {
    _key: 'rationale',
    uri: 'ff:rationale',
    label: 'Rationale',
    propertyType: 'datatype',
    domain: 'Thing',
    range: 'xsd:string',
    comment: 'Explanation for inferred values or decisions.',
  },
  {
    _key: 'confidence',
    uri: 'ff:confidence',
    label: 'Confidence',
    propertyType: 'datatype',
    domain: 'Thing',
    range: 'xsd:decimal',
    comment: '0.0-1.0 confidence score. Below threshold MUST trigger CRP.',
  },
  {
    _key: 'derivationMode',
    uri: 'ff:derivationMode',
    label: 'Derivation Mode',
    propertyType: 'datatype',
    domain: 'SpecificationArtifact',
    range: 'xsd:string',
    comment: 'How this artifact was derived: extracted, generated, pre-authored, architect-extracted.',
  },
  {
    _key: 'timestamp',
    uri: 'ff:timestamp',
    label: 'Timestamp',
    propertyType: 'datatype',
    domain: 'Thing',
    range: 'xsd:dateTime',
    comment: 'ISO 8601 timestamp.',
  },
  {
    _key: 'tokenUsage',
    uri: 'ff:tokenUsage',
    label: 'Token Usage',
    propertyType: 'datatype',
    domain: 'ExecutionArtifact',
    range: 'xsd:integer',
    comment: 'Tokens consumed by this execution artifact.',
  },
  {
    _key: 'repairCount',
    uri: 'ff:repairCount',
    label: 'Repair Count',
    propertyType: 'datatype',
    domain: 'SynthesisSession',
    range: 'xsd:integer',
    comment: 'Number of repair cycles in this synthesis session.',
  },
  {
    _key: 'passed',
    uri: 'ff:passed',
    label: 'Passed',
    propertyType: 'datatype',
    domain: 'CoverageReport | CritiqueReport | TestReport',
    range: 'xsd:boolean',
    comment: 'Whether this report passed validation.',
  },

  // BriefingScript required fields
  {
    _key: 'goal',
    uri: 'ff:goal',
    label: 'Goal',
    propertyType: 'datatype',
    domain: 'BriefingScript',
    range: 'xsd:string',
    comment: 'Primary objective of the BriefingScript.',
  },
  {
    _key: 'successCriteria',
    uri: 'ff:successCriteria',
    label: 'Success Criteria',
    propertyType: 'datatype',
    domain: 'BriefingScript',
    range: 'xsd:string',
    comment: 'Measurable conditions that define BriefingScript success.',
  },
  {
    _key: 'architecturalContext',
    uri: 'ff:architecturalContext',
    label: 'Architectural Context',
    propertyType: 'datatype',
    domain: 'BriefingScript',
    range: 'xsd:string',
    comment: 'Relevant background from decisions and codebase.',
  },
  {
    _key: 'strategicAdvice',
    uri: 'ff:strategicAdvice',
    label: 'Strategic Advice',
    propertyType: 'datatype',
    domain: 'BriefingScript',
    range: 'xsd:string',
    comment: 'High-level guidance for downstream agents.',
  },
  {
    _key: 'knownGotchas',
    uri: 'ff:knownGotchas',
    label: 'Known Gotchas',
    propertyType: 'datatype',
    domain: 'BriefingScript',
    range: 'xsd:string',
    comment: 'Pitfalls from lessons learned.',
  },
  {
    _key: 'validationLoop',
    uri: 'ff:validationLoop',
    label: 'Validation Loop',
    propertyType: 'datatype',
    domain: 'BriefingScript',
    range: 'xsd:string',
    comment: 'How to validate the BriefingScript outcome.',
  },

  // DetectorSpec required fields
  {
    _key: 'evidenceSources',
    uri: 'ff:evidenceSources',
    label: 'Evidence Sources',
    propertyType: 'datatype',
    domain: 'DetectorSpec',
    range: 'xsd:string',
    comment: 'Named evidence sources for the detector.',
  },
  {
    _key: 'directRules',
    uri: 'ff:directRules',
    label: 'Direct Rules',
    propertyType: 'datatype',
    domain: 'DetectorSpec',
    range: 'xsd:string',
    comment: 'Direct rules for the detector.',
  },
  {
    _key: 'regressionPolicy',
    uri: 'ff:regressionPolicy',
    label: 'Regression Policy',
    propertyType: 'datatype',
    domain: 'DetectorSpec',
    range: 'xsd:string',
    comment: 'Regression policy for the detector.',
  },

  // CritiqueReport fields
  {
    _key: 'mentorRulesChecked',
    uri: 'ff:mentorRulesChecked',
    label: 'Mentor Rules Checked',
    propertyType: 'datatype',
    domain: 'CritiqueReport',
    range: 'xsd:string',
    comment: 'Which MentorScript rules were checked during this review.',
  },
  {
    _key: 'content',
    uri: 'ff:content',
    label: 'Content',
    propertyType: 'datatype',
    domain: 'CodeArtifact',
    range: 'xsd:string',
    comment: 'File content of the code artifact.',
  },
  {
    _key: 'reviewType',
    uri: 'ff:reviewType',
    label: 'Review Type',
    propertyType: 'datatype',
    domain: 'CritiqueReport',
    range: 'xsd:string',
    comment: 'Type of review: semantic, code, etc.',
  },
]
