export const MAX_FEEDBACK_INFLUENCE = 0.35
export const DEVIATION_DRIFT_STEP = 0.12
export const MATCH_RELIEF_STEP = 0.05
export const DRIFT_CAP = 0.8
export const RECALIBRATION_POLICY_ID = "GOV-META-ADAPTIVE-PRESSURE-RECALIBRATION"
