
// Auto-generated by flue (target: cloudflare)
import { getPackagedSkills } from 'virtual:flue/packaged-skills';
import { env } from 'cloudflare:workers';
import { Agent, getAgentByName } from 'agents';
import {
  Bash,
  InMemoryFs,
  createFlueContext,
  InMemorySessionStore,
  InMemoryRunStore,
  createDurableRunStore,
  CLOUDFLARE_AGENT_INTERNAL_DISPATCH_PATH,
  CLOUDFLARE_WORKFLOW_INTERNAL_METADATA_PATH,
  createCloudflareAgentRuntime,
  createSqlSessionStore,
   SqliteEventStreamStore,
  bashFactoryToSessionEnv,
  resolveModel,
  handleWorkflowRequest,
  handleRunRouteRequest,
  handleStreamRead,
  handleStreamHead,
  failRecoveredRun,
  configureFlueRuntime,
  createDefaultFlueApp,
  hasRegisteredProvider,
} from '@flue/runtime/internal';
import {
  runWithCloudflareContext,
  cfSandboxToSessionEnv,
  getCloudflareAIBindingApiProvider,
  FlueRegistry,
  createCloudflareRunRegistry,
  resolveCloudflareExtension,
} from '@flue/runtime/cloudflare';
import { registerApiProvider, registerProvider } from '@flue/runtime';


import * as workflow_atom_execution_0 from "/Users/wes/Developer/function-factory/.flue/workflows/atom-execution.ts";
import userApp from "/Users/wes/Developer/function-factory/.flue/app.ts";
import * as userCloudflareModule from "/Users/wes/Developer/function-factory/.flue/cloudflare.ts";
export * from "/Users/wes/Developer/function-factory/.flue/cloudflare.ts";

// ─── Internal provider registrations ────────────────────────────────────────
// User `app.ts` imports are hoisted above this body, so a user-supplied
// `registerProvider('cloudflare', ...)` runs first; the guard below
// preserves it. The default enables Cloudflare's default AI Gateway,
// which the binding spins up on demand for the account.

registerApiProvider(getCloudflareAIBindingApiProvider());

if (!hasRegisteredProvider('cloudflare')) {
  registerProvider('cloudflare', {
    api: 'cloudflare-ai-binding',
    binding: env.AI,
    gateway: { id: 'default' },
  });
}

// ─── Config ─────────────────────────────────────────────────────────────────

const skills = {};
const packagedSkills = getPackagedSkills();
const systemPrompt = '';


function normalizeBuiltModules(agentModules, workflowModules) {
  const manifest = { agents: [], workflows: [] };
  const createdAgents = {};
  const dispatchAgentNames = new Map();
  const workflowHandlers = {};
  const localWorkflowHandlers = {};
  const agentRouteMiddleware = {};
  const workflowRouteMiddleware = {};
  for (const [name, mod] of Object.entries(agentModules)) {
    if (!mod.default || mod.default.__flueCreatedAgent !== true || typeof mod.default.initialize !== 'function') throw new Error('[flue] Agent "' + name + '" must default-export createAgent(...).');
    if (mod.route !== undefined && typeof mod.route !== 'function') throw new Error('[flue] Agent "' + name + '" route export must be a callable Hono middleware value.');
    const transports = {};
    if (typeof mod.route === 'function') transports.http = true;
    manifest.agents.push({ name, transports, created: true });
    createdAgents[name] = mod.default;
    const previousDispatchName = dispatchAgentNames.get(mod.default);
    if (previousDispatchName !== undefined) throw new Error('[flue] Agents "' + previousDispatchName + '" and "' + name + '" default-export the same created agent value. Use distinct createAgent(...) values for dispatchable agent modules.');
    dispatchAgentNames.set(mod.default, name);
    if (typeof mod.route === 'function') agentRouteMiddleware[name] = mod.route;
  }

  for (const [name, mod] of Object.entries(workflowModules)) {
    if (typeof mod.run !== 'function') throw new Error('[flue] Workflow "' + name + '" must export a callable run value.');
    if (mod.route !== undefined && typeof mod.route !== 'function') throw new Error('[flue] Workflow "' + name + '" route export must be a callable Hono middleware value.');
    const transports = {};
    if (typeof mod.route === 'function') transports.http = true;
    manifest.workflows.push({ name, transports });
    localWorkflowHandlers[name] = mod.run;
    if (transports.http) workflowHandlers[name] = mod.run;
    if (typeof mod.route === 'function') workflowRouteMiddleware[name] = mod.route;
  }

  return { manifest, createdAgents, dispatchAgentNames, workflowHandlers, localWorkflowHandlers, agentRouteMiddleware, workflowRouteMiddleware };
}


const agentModules = {

};
const workflowModules = {
  "atom-execution": workflow_atom_execution_0,
};
const normalized = normalizeBuiltModules(agentModules, workflowModules);
const { manifest, createdAgents, dispatchAgentNames, workflowHandlers, agentRouteMiddleware, workflowRouteMiddleware } = normalized;
const agentIdentities = {

};
const workflowIdentities = {
  "atom-execution": { bindingName: "FLUE_ATOM_EXECUTION_WORKFLOW", className: "FlueAtomExecutionWorkflow" },
};

const userCloudflare = userCloudflareModule;
const reservedCloudflareExportNames = new Set(["FlueAtomExecutionWorkflow","FlueRegistry"]);
for (const name of Object.keys(userCloudflare)) {
  if (name === 'default') continue;
  if (reservedCloudflareExportNames.has(name)) {
    throw new Error('[flue] cloudflare.ts export "' + name + '" conflicts with a Flue-generated Worker export. Rename the authored export.');
  }
}
const cloudflareHandlers = 'default' in userCloudflare ? userCloudflare.default : {};
if (typeof cloudflareHandlers !== 'object' || cloudflareHandlers === null || Array.isArray(cloudflareHandlers)) {
  throw new Error('[flue] cloudflare.ts default export must be an object containing non-HTTP Worker handlers.');
}
if ('fetch' in cloudflareHandlers) {
  throw new Error('[flue] cloudflare.ts default export must not define fetch. Use app.ts for custom HTTP handling.');
}

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

/**
 * Detect and wrap external sandbox instances (e.g. from @cloudflare/sandbox's
 * getSandbox()). Returns SessionEnv if the value looks like a Durable Object
 * RPC stub, null otherwise.
 *
 * NOTE on detection: The value returned by `getSandbox()` is a workerd RPC
 * Proxy. None of the obvious detection strategies work:
 *
 *   - Structural duck-typing (`'X' in stub`, `typeof stub.X === 'function'`):
 *     the proxy lies positively for any property name, so any check returns
 *     `true` regardless of what's actually on the remote.
 *   - `instanceof <UserSandboxClass>` (e.g. `Sandbox` from
 *     `@cloudflare/sandbox`): the user's class only exists on the in-DO
 *     side; over RPC the caller gets a generic stub.
 *   - `instanceof DurableObject` (imported from `cloudflare:workers`): the
 *     stub's prototype chain has a class *named* `DurableObject`, but it's a
 *     workerd-internal class with a different identity than the importable
 *     one. `instanceof` checks identity, not name, so it returns `false`.
 *
 * The one signal that does work — verified by runtime probe — is the string
 * name of the prototype's constructor. Workerd's internal RPC stub class is
 * named `DurableObject`, and `Object.getPrototypeOf(stub).constructor.name`
 * returns that string. This is a heuristic (it relies on a workerd-internal
 * naming convention, not a contractual API), but it's empirically correct
 * today and will misroute only if a user passes some other DO stub to
 * `createAgent(() => ({ sandbox }))` — in which case `cfSandboxToSessionEnv` will fail
 * loudly on first method call.
 */
function resolveSandbox(sandbox) {
  if (
    sandbox &&
    typeof sandbox === 'object' &&
    Object.getPrototypeOf(sandbox)?.constructor?.name === 'DurableObject'
  ) {
    return cfSandboxToSessionEnv(sandbox);
  }
  return null;
}

const memoryWorkflowSessionStore = new InMemorySessionStore();
const memoryRunStore = new InMemoryRunStore();
const INTERNAL_DISPATCH_PATH = CLOUDFLARE_AGENT_INTERNAL_DISPATCH_PATH;
const INTERNAL_RUN_METADATA_PATH = CLOUDFLARE_WORKFLOW_INTERNAL_METADATA_PATH;
const dispatchQueue = {
  async enqueue(input) {
    const identity = agentIdentities[input.agent];
    const binding = env?.[identity?.bindingName];
    if (!binding) throw new Error('[flue] dispatch() target agent "' + input.agent + '" Durable Object binding is unavailable.');
    const response = await fetchAgent(binding, input.id, new Request('https://flue.invalid' + INTERNAL_DISPATCH_PATH, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(input),
    }));
    if (!response.ok) throw new Error('[flue] dispatch() target agent "' + input.agent + '" rejected durable admission with status ' + response.status + '.');
    return response.json();
  },
};

function createContextForRequest(id, runId, payload, doInstance, req, defaultStore, initialEventIndex, dispatchId) {
  return createFlueContext({
    id,
    runId,
    dispatchId,
    payload,
    env: doInstance?.env ?? {},
    req,
    initialEventIndex,
    agentConfig: {
      systemPrompt, skills, packagedSkills, model: undefined, resolveModel,
    },
    createDefaultEnv,
    defaultStore,
    resolveSandbox,
  });
}

function createAgentContextForRequest(executionStore, id, payload, doInstance, req, initialEventIndex, dispatchId) {
  return createFlueContext({
    id,
    payload,
    env: doInstance?.env ?? {},
    req,
    initialEventIndex,
    dispatchId,
    agentConfig: {
      systemPrompt, skills, packagedSkills, model: undefined, resolveModel,
    },
    createDefaultEnv,
    defaultStore: executionStore.sessions,
    resolveSandbox,
    submissionStore: executionStore.submissions,
  });
}

function createWorkflowContextForRequest(id, runId, payload, doInstance, req, initialEventIndex, dispatchId) {
  const sql = doInstance?.ctx?.storage?.sql;
  const defaultStore = sql ? createSqlSessionStore(sql) : memoryWorkflowSessionStore;
  return createContextForRequest(id, runId, payload, doInstance, req, defaultStore, initialEventIndex, dispatchId);
}

function createRunStoreForRequest(doInstance) {
  return doInstance?.ctx?.storage?.sql
    ? createDurableRunStore(doInstance.ctx.storage.sql)
    : memoryRunStore;
}

function createRunRegistryForRequest(reqEnv) {
  return createCloudflareRunRegistry(reqEnv?.FLUE_REGISTRY);
}

async function fetchAgent(binding, instanceId, request) {
  return (await getAgentByName(binding, instanceId)).fetch(request);
}

function runWithInstanceContext(doInstance, identity, fn) {
  return runWithCloudflareContext(
    {
      env: doInstance.env,
      agentInstance: doInstance,
      storage: doInstance.ctx.storage,
      durableObjectIdentity: createDurableObjectIdentity(doInstance, identity),
    },
    fn,
  );
}

function createDurableObjectIdentity(doInstance, identity) {
  return {
    bindingName: identity.bindingName,
    className: identity.className,
    name: doInstance.name,
    id: doInstance.ctx.id.toString(),
  };
}

const eventStreamStores = new WeakMap();

function createEventStreamStoreForInstance(doInstance) {
  const existing = eventStreamStores.get(doInstance);
  if (existing) return existing;
  const sql = doInstance?.ctx?.storage?.sql;
  if (!sql) {
    throw new Error('[flue] Durable Object SQLite storage is unavailable — cannot create the event stream store. Flue Durable Object classes require SQLite-backed storage.');
  }
  const store = new SqliteEventStreamStore(sql);
  eventStreamStores.set(doInstance, store);
  return store;
}

const cloudflareAgents = createCloudflareAgentRuntime({
  createdAgents,
  createContext: ({ executionStore, instance, payload, request, initialEventIndex, dispatchId }) =>
    createAgentContextForRequest(executionStore, instance.name, payload, instance, request, initialEventIndex, dispatchId),
  runWithInstanceContext: (instance, agentName, fn) => runWithInstanceContext(instance, agentRuntimeIdentity(agentName), fn),
  createEventStreamStore: (instance) => createEventStreamStoreForInstance(instance),
});

function assertAgentsDurabilityApi(doInstance, method) {
  if (typeof doInstance[method] !== 'function') {
		throw new Error(
			'[flue] The installed "agents" package does not provide the required Cloudflare Agents SDK method "' +
				method +
				'". Install or upgrade the "agents" package in your project.',
		);
	}
}

async function handleFlueWorkflowFiberRecovered(ctx, doInstance, workflowName) {
  if (!ctx.name || ctx.name !== 'flue:workflow:' + doInstance.name) return;
  const interruptedRunId = doInstance.name;
  const runStore = createRunStoreForRequest(doInstance);
  await failRecoveredRun({
    owner: { kind: 'workflow', workflowName, instanceId: interruptedRunId },
    id: interruptedRunId,
    runId: interruptedRunId,
    request: new Request('https://flue.invalid/workflows/' + encodeURIComponent(workflowName), { method: 'POST' }),
    error: new Error('Flue workflow execution was interrupted. Start a new workflow run explicitly if retry is appropriate.'),
    runStore,
    runRegistry: createRunRegistryForRequest(doInstance.env),
    eventStreamStore: createEventStreamStoreForInstance(doInstance),
    createContext: (id_, recoveredRunId, payload, req, initialEventIndex) => createWorkflowContextForRequest(id_, recoveredRunId, payload, doInstance, req, initialEventIndex),
  });
}

async function dispatchWorkflow(request, doInstance, workflowName) {
  // The DO room name is the workflow instance id. For workflows that
  // equals the run id (one run per instance), so callers reach this DO
  // either by starting a new run (POST /workflows/:name → routed by the
  // outer worker) or by hitting a /runs/:runId subroute on an existing
  // instance.
  const instanceId = doInstance.name;
  const runRoute = parseRunRoute(request);
  if (runRoute) {
    // DS stream read (GET/HEAD on /runs/:runId) — use EventStreamStore.
    if (runRoute.action === 'ds-stream') {
      const store = createEventStreamStoreForInstance(doInstance);
      const streamPath = 'runs/' + runRoute.runId;
      if (request.method === 'HEAD') return await handleStreamHead(store, streamPath);
      return handleStreamRead({ store, path: streamPath, request });
    }
    return handleRunRouteRequest({
      owner: { kind: 'workflow', workflowName, instanceId },
      runId: instanceId,
      runStore: createRunStoreForRequest(doInstance),
    });
  }

  if (!parseWorkflowStart(request, workflowName)) return null;
  const handler = workflowHandlers[workflowName];
  if (!handler) return null;
  const identity = workflowRuntimeIdentity(workflowName);
  return runWithInstanceContext(doInstance, identity, () => handleWorkflowRequest({
      request,
      workflowName,
      runId: instanceId,
      handler,
      runStore: createRunStoreForRequest(doInstance),
      runRegistry: createRunRegistryForRequest(doInstance.env),
      eventStreamStore: createEventStreamStoreForInstance(doInstance),
      createContext: (id_, runId, payload, req, initialEventIndex, dispatchId) => createWorkflowContextForRequest(id_, runId, payload, doInstance, req, initialEventIndex, dispatchId),
      startWorkflowAdmission: (runId, run) => {
        assertAgentsDurabilityApi(doInstance, 'runFiber');
        return doInstance.runFiber('flue:workflow:' + runId, () => runWithInstanceContext(doInstance, identity, run));
      },
    }));
}



function workflowRuntimeIdentity(workflowName) {
  return workflowIdentities[workflowName];
}

function agentRuntimeIdentity(agentName) {
  return agentIdentities[agentName];
}

function parseWorkflowStart(request, workflowName) {
  if (request.method !== 'POST') return false;
  const url = new URL(request.url);
  const segments = url.pathname.split('/').filter(Boolean);
  if (segments.length !== 2 || segments[0] !== 'workflows') return false;
  return decodeURIComponent(segments[1] || '') === workflowName;
}

function parseRunRoute(request) {
  const url = new URL(request.url);
  if (url.pathname === INTERNAL_RUN_METADATA_PATH) return { action: 'get' };
  const segments = url.pathname.split('/').filter(Boolean);
  if (segments.length < 2 || segments[0] !== 'runs') return null;
  let runId;
  try {
    runId = decodeURIComponent(segments[1] || '');
  } catch {
    return null;
  }
  const child = segments[2];
  if (!runId) return null;
  if (!child) {
    const method = request.method;
    // GET/HEAD on /runs/:runId → DS stream read. The outer worker rejects
    // other methods before forwarding, so nothing else routes here.
    if (method === 'GET' || method === 'HEAD') return { action: 'ds-stream', runId };
    return null;
  }
  return null;
}

// ─── Per-Agent / Per-Workflow Durable Object Classes ──────────────────────


const workflowExtension0 = resolveCloudflareExtension(workflowModules["atom-execution"], "atom-execution", 'Workflow');
const FlueAtomExecutionWorkflow = class FlueAtomExecutionWorkflow extends workflowExtension0.base(Agent) {
  async onRequest(request) {
    return dispatchWorkflow(request, this, "atom-execution");
  }

  async onFiberRecovered(ctx) {
    if (ctx.name?.startsWith('flue:workflow:')) {
      return handleFlueWorkflowFiberRecovered(ctx, this, "atom-execution");
    }
    if (typeof super.onFiberRecovered === 'function') {
      return super.onFiberRecovered(ctx);
    }
  }
};
const WrappedFlueAtomExecutionWorkflow = workflowExtension0.wrap(FlueAtomExecutionWorkflow);
export { WrappedFlueAtomExecutionWorkflow as FlueAtomExecutionWorkflow };

export { FlueRegistry };

// ─── Runtime seed ───────────────────────────────────────────────────────────

configureFlueRuntime({
  target: 'cloudflare',
  devMode: import.meta.env.DEV,
  runtimeVersion: "0.11.0",
  manifest,
  dispatchQueue,
  resolveDispatchAgentName: (agent) => dispatchAgentNames.get(agent),
  agentRouteMiddleware,
  workflowRouteMiddleware,
  routeAgentRequest: async (request, reqEnv, target) => {
    const binding = reqEnv?.[agentIdentities[target.agentName]?.bindingName];
    if (!binding) return null;
    return fetchAgent(binding, target.instanceId, request);
  },
  routeWorkflowRequest: async (request, reqEnv, target) => {
    const binding = reqEnv?.[workflowIdentities[target.workflowName]?.bindingName];
    if (!binding) return null;
    return fetchAgent(binding, target.instanceId, request);
  },
  createRunRegistryForRequest,
  routeRunRequest: async (request, reqEnv, target) => {
    if (target.kind !== 'workflow') return null;
    const binding = reqEnv?.[workflowIdentities[target.workflowName]?.bindingName];
    if (!binding) return null;
    return fetchAgent(binding, target.instanceId, request);
  },
});

// ─── App composition ────────────────────────────────────────────────────────

// User-supplied app.ts. Their default export owns the entire request
// pipeline — the worker just verifies a fetch method exists and pipes
// through. The default flue() handler is available for them to mount
// however they want; this file does not impose a composition.
const flueApp = userApp;
if (!flueApp || typeof flueApp.fetch !== 'function') {
  throw new Error(
    '[flue] app.ts default export must be a Hono app or an object with a fetch(request, env, ctx) method.'
  );
}

export default {
  ...cloudflareHandlers,
  fetch(request, env, ctx) {
    return flueApp.fetch(request, env, ctx);
  },
};
