export const HIGH_STRESS_DRIFT_THRESHOLD = 0.45
export const HIGH_STRESS_DEVIATION_THRESHOLD = 3
export const HIGH_STRESS_REPEAT_THRESHOLD = 2
export const MODERATE_STRESS_DRIFT_THRESHOLD = 0.25
export const MODERATE_STRESS_DEVIATION_THRESHOLD = 2
export const MODERATE_STRESS_REPEAT_THRESHOLD = 1
export const META_GOV_POLICY_ID = "GOV-META-POLICY-EVOLUTION"
