export const MATCH_REWARD_STEP = 0.08
export const DEVIATION_PENALTY_STEP = 0.12
export const RELIABILITY_BASELINE = 0.5
export const MAX_POSITIVE_BIAS = 0.15
export const MAX_NEGATIVE_BIAS = -0.2
export const DRIFT_PENALTY_MULTIPLIER = 0.2
export const BIAS_POLICY_ID = "GOV-META-SELECTION-BIAS-ADAPTATION"
